# This is a basic workflow that is manually triggered

name: Run a specific test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'test file'
        # Default value if no value is explicitly provided
        default: 'cypress/**/*cy.js'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    name: Running Tests
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          spec: ${{ inputs.name }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-report
          path: cypress/reports/html
